import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { JahshanListeningPlayer } from './JahshanListeningPlayer';
import collection from '../data/jahshanCollection.json';
const tracks = collection.files.filter(file => file.relativePath.startsWith('Audio/3- Sample Test 1/'));
const data = (track: typeof tracks[number], text: string) => ({ trackId: track.id, sourceSha256: track.sha256, kind: 'automatic-transcription', segments: [{ start: 0, end: 5, text }, { start: 5, end: 10, text: 'Second sentence.' }] });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });
it('loads the matching transcript, highlights playback and seeks by timestamp', async () => {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, json: async () => data(tracks[0], 'First original sentence.') }));
  const view = render(<JahshanListeningPlayer track={tracks[0]} audioUrl="blob:original" />);
  await screen.findByText('First original sentence.');
  const audio = view.container.querySelector('audio')!;
  Object.defineProperty(audio, 'duration', { configurable: true, value: 120 });
  fireEvent.loadedMetadata(audio);
  fireEvent.timeUpdate(audio, { target: { currentTime: 6 } });
  expect(screen.getByRole('button', { name: '0:05 Second sentence.' })).toHaveAttribute('aria-current', 'true');
  fireEvent.click(screen.getByRole('button', { name: '0:00 First original sentence.' }));
  expect(audio.currentTime).toBe(0);
  expect(screen.getByRole('link', { name: 'Download transcript' })).toHaveAttribute('download', expect.stringContaining('-transcript.txt'));
});
it('clears the old script immediately when the recording changes and rejects a mismatched transcript', async () => {
  const fetcher = vi.fn().mockResolvedValueOnce({ ok: true, json: async () => data(tracks[0], 'Old track sentence.') }).mockResolvedValueOnce({ ok: true, json: async () => data(tracks[0], 'Wrong recording text.') });
  vi.stubGlobal('fetch', fetcher);
  const view = render(<JahshanListeningPlayer track={tracks[0]} />);
  await screen.findByText('Old track sentence.');
  view.rerender(<JahshanListeningPlayer track={tracks[1]} />);
  expect(screen.queryByText('Old track sentence.')).not.toBeInTheDocument();
  await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('unavailable'));
  expect(screen.queryByText('Wrong recording text.')).not.toBeInTheDocument();
});
it('plays the hosted recording without local files and gives a retry option on failure', async () => {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, json: async () => data(tracks[0], 'Hosted track sentence.') }));
  const view = render(<JahshanListeningPlayer track={tracks[0]} />);
  await screen.findByText('Hosted track sentence.');
  const audio = view.container.querySelector('audio')!;
  Object.defineProperty(audio, 'duration', { configurable: true, value: 120 });
  fireEvent.loadedMetadata(audio);
  expect(audio.getAttribute('src')).toMatch(new RegExp(`jahshan-audio/${tracks[0].id}\\.m4a$`));
  expect(screen.getByRole('button', { name: '0:05 Second sentence.' })).toBeEnabled();
  fireEvent.click(screen.getByRole('button', { name: '0:05 Second sentence.' }));
  expect(audio.currentTime).toBe(5);
  fireEvent.error(audio);
  expect(screen.getByRole('alert')).toHaveTextContent('could not load');
  expect(screen.getByRole('link', { name: 'Open original recording ↗' })).toHaveAttribute('href', tracks[0].url);
  const retry = vi.spyOn(audio, 'load').mockImplementation(() => {});
  fireEvent.click(screen.getByRole('button', { name: 'Retry audio' }));
  expect(retry).toHaveBeenCalledOnce();
  expect(screen.queryByRole('alert')).not.toBeInTheDocument();
  view.rerender(<JahshanListeningPlayer track={tracks[1]} />);
  expect(view.container.querySelector('audio')?.getAttribute('src')).toContain(`${tracks[1].id}.m4a`);
});

it('uses independent controls for play, pause, seeking and volume without Safari icon buttons', async () => {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, json: async () => data(tracks[0], 'Control test sentence.') }));
  const view = render(<JahshanListeningPlayer track={tracks[0]} />);
  await screen.findByText('Control test sentence.');
  Object.defineProperty(view.container.querySelector('.transcript-box')!, 'scrollTo', { value: vi.fn() });
  const audio = view.container.querySelector('audio')!;
  expect(audio).not.toHaveAttribute('controls');
  expect(screen.getByRole('slider', { name: 'Recording position' })).toBeDisabled();
  Object.defineProperty(audio, 'duration', { configurable: true, value: 120 });
  Object.defineProperty(audio, 'paused', { configurable: true, value: true });
  fireEvent.loadedMetadata(audio);
  const play = vi.spyOn(audio, 'play').mockImplementation(async () => {
    Object.defineProperty(audio, 'paused', { configurable: true, value: false });
    fireEvent.play(audio);
  });
  const pause = vi.spyOn(audio, 'pause').mockImplementation(() => fireEvent.pause(audio));
  fireEvent.click(screen.getByRole('button', { name: 'Play recording' }));
  expect(play).toHaveBeenCalledOnce();
  fireEvent.click(await screen.findByRole('button', { name: 'Pause recording' }));
  expect(pause).toHaveBeenCalledOnce();
  fireEvent.change(screen.getByRole('slider', { name: 'Recording position' }), { target: { value: '110' } });
  fireEvent.click(screen.getByRole('button', { name: 'Forward 15 seconds' }));
  expect(audio.currentTime).toBe(120);
  fireEvent.click(screen.getByRole('button', { name: 'Back 15 seconds' }));
  expect(audio.currentTime).toBe(105);
  fireEvent.change(screen.getByRole('slider', { name: 'Volume' }), { target: { value: '0.5' } });
  expect(audio.volume).toBe(0.5);
});
it('handles a rejected play request without an unhandled promise or a false missing-file error', async () => {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, json: async () => data(tracks[0], 'Play rejection sentence.') }));
  const view = render(<JahshanListeningPlayer track={tracks[0]} />);
  await screen.findByText('Play rejection sentence.');
  vi.spyOn(view.container.querySelector('audio')!, 'play').mockRejectedValue(new DOMException('Blocked', 'NotAllowedError'));
  fireEvent.click(screen.getByRole('button', { name: 'Play recording' }));
  expect(await screen.findByRole('status')).toHaveTextContent('Playback did not start');
  expect(screen.queryByRole('alert')).not.toBeInTheDocument();
});
