/** AUTO-GENERATED by scripts/import-ashgan-assets.py — do not edit by hand. */
import type { AshganLibraryItem } from '../types';

export const ashganLibraryImportedAt = "2026-05-30";
export const ashganLibrarySourceHandles = ["OETDoctorsHub", "OETDoctors", "officialoet", "DrAshgan"] as const;

export const ashganLibraryItems: AshganLibraryItem[] = [
];
